name: name名字
run-name: run-name运行名字
on: [push]
env:
  RUNNER_DEBUG: '1'
jobs:
  update-release:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: msys2 {0}
    steps:
      - run: |
          ldd --version
      - run: |
          sudo apt-get update &&sudo  apt-get install -y gcc g++ nodejs lsb-release
      - run: |
          uname -a
          lsb_release -a
      - run: |
          gcc --version
          g++ --version
      - run: |
          node --version

      - run: |
          type node
          node --version
          ls -lh
          echo  '1232' > xxx.exe
          # echo  '123' > b.json
          # echo  '123' > c.deb
          # echo  '123' > d.tar.gz
          ls -lh
          # env
          # node -e "console.log(process.env)"
          # cat /var/run/act/workflow/envs.txt
