name: name名字
run-name: run-name运行名字
on: [push]
env:
  RUNNER_DEBUG: '1'
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: whatever
      - name: pull-code
        uses: actions/checkout@v4
        with:
          repository: 'index-tts/index-tts'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python --version
          conda create -n index-tts python=3.10
          conda activate index-tts
          conda install -c conda-forge ffmpeg
          conda install -c conda-forge pynini==2.1.6
          pip install WeTextProcessing --no-deps
          pip install -e .
          indextts --help