name: name名字
run-name: py-env
on: [push]
permissions:
  contents: write
env:
  RUNNER_DEBUG: '1'
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: whatever
      - name: pull-code
        uses: actions/checkout@v4
        with:
          repository: 'index-tts/index-tts'
    #   - name: Compress a folder
    #     run: Compress-Archive -Path "." -DestinationPath "abc.zip"
    #   - uses: actions/setup-python@v5
    #     with:
    #       python-version: '3.10'
      - run: |
          python --version
          conda create -p ../tts-env/.venv python=3.10
          conda activate ../tts-env/.venv
          conda install -c conda-forge ffmpeg
          conda install -c conda-forge pynini==2.1.6
          pip install WeTextProcessing --no-deps
          pip install .
          indextts --help
        #   ls
        #   tree
      - name: Compress a folder
        run: Compress-Archive -Path "..\tts-env" -DestinationPath "output.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: output.zip
          tag_name: 1.0.1
