name: Release-test

on: [push]
env:
  RUNNER_DEBUG: '1'
  ANCHOR_VERSION: '1.0.0'
permissions:
  contents: write
jobs:
  joba:
    runs-on: ubuntu-latest

    steps:
      - run: |
          touch xx yy
      - name: release-1
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: '**/*'
          tag_name: ${{env.ANCHOR_VERSION}}
      - name: release-1
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: '**/*'
          tag_name: ${{env.ANCHOR_VERSION}}
