name: zstd-test
run-name: zstd-test
on: [push]
permissions:
  contents: write
env:
  RUNNER_DEBUG: '1'
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - name: pull-code
        uses: actions/checkout@v4
        with:
          repository: 'index-tts/index-tts'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: wszgrcy/actions-pkg@1.1.1
        with:
          dir: '.'
          outputPath: ./abcd.tar.zstd
          cleanPaths: |
            **/*.py

      # - run: |
      #     ls
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: abcd.tar.zstd
      #     tag_name: 1.0.1
