name: name名字
run-name: zstd-test
on: [push]
permissions:
  contents: write
env:
  RUNNER_DEBUG: '1'
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - name: pull-code
        uses: actions/checkout@v4
        with:
          repository: 'index-tts/index-tts'
      - uses: wszgrcy/actions-pkg@1.0.22
        with:
          dir: ./index-tts
          outputPath: ./abcd.zstd
          cleanPaths: |
            **/*.py
            b
            c
      - run: |
          ls
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: abcd.zstd
          tag_name: 1.0.1